---
title: Robin Rendle
url: http://robinrendle.com
timezone: Europe/London
collections:
  essays:
    title: Essays
    output: true
  notes:
    title: Notes
    output: true
  posts:
    title: Posts
    output: true
  reading:
    title: Reading
    output: true
    order: date
    values:
      layout: reading
  stories:
    title: Stories
    output: true
  talks:
    title: Talks
    output: true
  uploads:
    title: Uploads
    output: false
  work:
    title: Work
    output: true
  adventures:
    title: Adventures in Typography
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/notes/:title/"
    layout: default
- scope:
    path: ''
    type: notes
  values:
    permalink: "/notes/"
    layout: notes
- scope:
    path: ''
    type: reading
  values:
    permalink: "/reading/:title/"
    layout: default
- scope:
    path: ''
    type: essays
  values:
    permalink: "/essays/:title/"
    layout: essays-detail
- scope:
    path: ''
    type: work
  values:
    permalink: "/work/:title/"
    layout: work-detail
- scope:
    path: ''
    type: adventures
  values:
    permalink: "/adventures/"
    layout: adventures
- scope:
    path: ''
    type: talks
  values:
    permalink: "/talks/:title/"
    layout: talks-detail
name: Robin Rendle
description: Typography, design and front-end development.
permalink: pretty
current_location: Nottingham, UK
markdown: kramdown
exclude:
- node_modules
- package.json
- npm-debug.log
- gulpfile.js
- sass
