---
title: Robin Rendle
url: http://robinrendle.com
timezone: Europe/London
collections:
  essays:
    title: Essays
    output: true
  posts:
    title: Posts
    output: true
  reading:
    title: Reading
    output: true
    order: date
    values:
      layout: wonk
  stories:
    title: Stories
    output: true
  uploads:
    title: Uploads
    output: false
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/notes/:title/"
    layout: default
- scope:
    path: ''
    type: reading
  values:
    permalink: "/reading/:title/"
    layout: default
- scope:
    path: ''
    type: essays
  values:
    permalink: "/essays/:title/"
    layout: essays-detail
- scope:
    path: ''
    type: work
  values:
    permalink: "/work/:title/"
    layout: work-detail
permalink: pretty
current_location: Nottingham, UK
markdown: redcarpet
exclude:
- node_modules
- package.json
- npm-debug.log
- gulpfile.js
- sass
redcarpet:
  extensions:
  - autolink
  - fenced_code_blocks
  - lax_spacing
  - strikethrough
  - superscript
  - tables
  - footnotes
  - highlight
