[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/essays/futures-of-typography"
  to = "/essays/the-futures-of-typography"

[[redirects]]
  from = "/essays/new-web-typography/"
  to = "/essays/the-new-web-typography"
