[build]
  command = "astro build"
  publish = "dist"

[[redirects]]
  from = "/essays/futures-of-typography"
  to = "/essays/the-futures-of-typography"

[[redirects]]
  from = "/essays/new-web-typography/"
  to = "/essays/the-new-web-typography"

[[redirects]]
  from = "/feed.xml"
  to = "/feed/notes.xml"