backend:
  name: git-gateway
  branch: master 
media_folder: "uploads"
publish_mode: editorial_workflow
collections:
  - name: "notes" 
    label: "Notes"
    folder: "_posts" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "City", name: "city", widget: "string", default: "San Francisco"}
      - {label: "Country", name: "country", widget: "string", default: "California"}
      - {label: "Extract", name: "extract", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}