backend:
  name: git-gateway
  branch: master 
media_folder: "uploads"
collections:
  - name: "notes" 
    label: "Notes"
    folder: "_posts" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "City", name: "city", widget: "string"}
      - {label: "Country", name: "country", widget: "string"}
      - {label: "Tag", name: "tag", widget: "string" }
      - {label: "Body", name: "body", widget: "markdown"}