backend:
  name: git-gateway
  branch: main
media_folder: "images"
publish_mode: editorial_workflow
collections:
  - name: "notes"
    label: "Notes"
    folder: "src/pages/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "City",
          name: "city",
          widget: "string",
          default: "San Francisco",
        }
      - {
          label: "Country",
          name: "country",
          widget: "string",
          default: "California",
        }
      - {
          label: "Layout",
          name: "layout",
          widget: "string",
          default: "../../layouts/notes.astro",
        }
      - { label: "Extract", name: "extract", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
